name: Sync Docs to Wiki

on:
  push:
    branches:
      - develop
    paths:
      - 'docs/**/*.md'

jobs:
  sync-to-wiki:
    runs-on: ubuntu-latest
    ## Might not be needed in an organization level setting
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone Wiki repository
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki

      - name: Sync docs to wiki
        run: |
          cp -rf docs/ wiki/
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          if [ -n "$(git status)" ]; then
            git add .
            git commit -m "Sync Wiki with new changes"
            git push origin HEAD
          else
            echo "No changes to commit"
          fi
